spring.application.name=javaWebSystem

# Thymeleaf(HTML)のキャッシュをオフにする（開発時のみ）
spring.thymeleaf.cache=false

# 静的リソース（CSS/JS）のキャッシュもオフにする
spring.devtools.livereload.enabled=true

# 全体のログレベルをINFOに設定
logging.level.root=INFO

# 自分の作ったパッケージだけDEBUGレベルにする
logging.level.com.example.demo=DEBUG

# H2コンソールを有効にする
spring.h2.console.enabled=true
# ブラウザからアクセスするパス
spring.h2.console.path=/h2-console
# DBの接続先（メモリ上に保存）
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# 実行されたSQLがターミナルで見える様にする
spring.jpa.show-sql=true

debug=true

# 起動時の膨大なレポートを出さない様にする
logging.level.org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger=OFF